---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/dynote99/public_html/
    - export DEPLOYPATH=/home1/dynote99/repositories/dynotest
    - /bin/cp * $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R ajax $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
